### ISSUE TITLE
Is there a WUI for this? - Not actually a issue

### ISSUE THREAD

**Issue by maufc** [Legobas/mqtt-timer#2]
Hi.
I'll be wonder if there is some kind of Web User Interface for this great application.
It would be quite simple on a first view, but I am sure it may become a new complete app.
Thanks!

**Comment by maufc** [comment]
Hi.
No body?

**Comment by Legobas** [comment]
I'm not sure why you would want a user interface, maybe for the configuration?
In a linux or docker environment it is very common to use configuration files which you can edit in a shell.
But if you want a front-end for programmable timers I can recommend node-red as I'm using it myself.

**Comment by maufc** [comment]
Hi. Thanks for your answer.
Yes, I would need a front-end application. Sure, I can use node-red but I was thinking on something like a web manage interface for different devices, timers, etc.
Definitely, I will look that kind of solution and it might use mqtt-timer
Thanks again!
